# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

OT_UNKNOWN = 0  # type: Literal[0]
MARKET = 1  # type: Literal[1]
LIMIT = 2  # type: Literal[2]
OT_RESERVED = 3  # type: Literal[3]
