# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

UP = 0  # type: Literal[0]
DOWN = 1  # type: Literal[1]
LEFT = 2  # type: Literal[2]
RIGHT = 3  # type: Literal[3]
