# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

MosaicLevy_Absolute = 1  # type: Literal[1]
MosaicLevy_Percentile = 2  # type: Literal[2]
