# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

SupplyChange_Increase = 1  # type: Literal[1]
SupplyChange_Decrease = 2  # type: Literal[2]
