# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class OntologyTxAttribute(p.MessageType):

    def __init__(
        self,
        usage: int = None,
        data: bytes = None,
    ) -> None:
        self.usage = usage
        self.data = data

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('usage', p.UVarintType, 0),
            2: ('data', p.BytesType, 0),
        }
