# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

ASK = 0  # type: Literal[0]
DEVICE = 1  # type: Literal[1]
HOST = 2  # type: Literal[2]
