# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

ScrambledWords = 0  # type: Literal[0]
Matrix = 1  # type: Literal[1]
