# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

TXINPUT = 0  # type: Literal[0]
TXOUTPUT = 1  # type: Literal[1]
TXMETA = 2  # type: Literal[2]
TXFINISHED = 3  # type: Literal[3]
TXEXTRADATA = 4  # type: Literal[4]
