# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

Yay = 0  # type: Literal[0]
Nay = 1  # type: Literal[1]
Pass = 2  # type: Literal[2]
