# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

Bip39 = 0  # type: Literal[0]
Slip39_Basic = 1  # type: Literal[1]
Slip39_Advanced = 2  # type: Literal[2]
