# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

SPENDADDRESS = 0  # type: Literal[0]
SPENDMULTISIG = 1  # type: Literal[1]
EXTERNAL = 2  # type: Literal[2]
SPENDWITNESS = 3  # type: Literal[3]
SPENDP2SHWITNESS = 4  # type: Literal[4]
