# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

ImportanceTransfer_Activate = 1  # type: Literal[1]
ImportanceTransfer_Deactivate = 2  # type: Literal[2]
