# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

CosignatoryModification_Add = 1  # type: Literal[1]
CosignatoryModification_Delete = 2  # type: Literal[2]
