# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class OntologySignedTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 355

    def __init__(
        self,
        signature: bytes = None,
        payload: bytes = None,
    ) -> None:
        self.signature = signature
        self.payload = payload

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('signature', p.BytesType, 0),
            2: ('payload', p.BytesType, 0),
        }
