# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

Current = 1  # type: Literal[1]
NewFirst = 2  # type: Literal[2]
NewSecond = 3  # type: Literal[3]
