# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

DISABLE = 0  # type: Literal[0]
ENABLE = 1  # type: Literal[1]
REFRESH = 2  # type: Literal[2]
