# Automatically generated by pb2py
# fmt: off

if __debug__:
    try:
        from typing_extensions import Literal
    except ImportError:
        pass

Plain = 0  # type: Literal[0]
Matrix9 = 1  # type: Literal[1]
Matrix6 = 2  # type: Literal[2]
